[workspace]
resolver = "2"
members = [
    "crates/sal-flat",
    "crates/sal-engine",
    "crates/sal-syntax",
    "crates/sal-core",
    "crates/sal-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-2.0"
repository = "https://github.com/GaloisInc/sal-rs"

[workspace.dependencies]
num-bigint = "0.4"
num-rational = "0.4"
num-traits = "0.2"
